# Generated by Django 6.0.6 on 2026-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_landingpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioimage',
            name='web_image',
            field=models.ImageField(blank=True, null=True, upload_to='studio/web/%Y/%m/', verbose_name='صورة العرض المضغوطة'),
        ),
    ]
